In [2]:
from keras.datasets import mnist
import cv2
import numpy as np
import pandas as pd
import tensorflow as tf

(xtrain, ytrain), (xtest, ytest) = mnist.load_data()

In [10]:
xtrain.shape

(60000, 784)

In [3]:
#reshaping data as needed by the model
xtrain=np.reshape(xtrain,(-1,28*28))
xtest=np.reshape(xtest,(-1,28*28))
# ytrain = np.reshape(ytrain,(-1,10))
# ytest = np.reshape()
xtrain.shape,xtest.shape,ytrain.shape,ytest.shape

((60000, 784), (10000, 784), (60000,), (10000,))

In [4]:
#normalising 
xtrain=xtrain/255
xtest=xtest/255

In [5]:
# #implementing one hot encoding
# from keras.utils.np_utils import to_categorical
# y_train = to_categorical(ytrain, num_classes=10)
# y_test = to_categorical(ytest, num_classes=10)

In [6]:
from sklearn.svm import SVC
classifier = SVC(kernel='linear',random_state = 0)
classifier.fit(xtrain,ytrain)

SVC(kernel='linear', random_state=0)

In [8]:
#Making the Confusion Matrix

from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(xtest)
cm = confusion_matrix(ytest, y_pred)
print(cm) 
accuracy_score(ytest, y_pred)

[[ 957    0    4    1    1    6    9    1    0    1]
 [   0 1122    3    2    0    1    2    1    4    0]
 [   8    6  967   11    3    3    7    8   17    2]
 [   4    3   16  947    1   16    0    9   12    2]
 [   1    1   10    1  942    2    4    2    3   16]
 [  10    4    3   36    6  803   13    1   14    2]
 [   9    2   13    1    5   16  910    1    1    0]
 [   1    8   21   10    8    1    0  957    3   19]
 [   8    4    6   25    7   26    6    7  877    8]
 [   7    7    2   11   33    4    0   18    5  922]]


0.9404